# Generated by Django 4.0 on 2022-01-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmanager',
            name='account_type',
            field=models.CharField(choices=[('Savings account', 'Savings account'), ('Current Account', 'Current Account'), ('Fixed Account', 'Fixed Account')], default=0, max_length=250),
        ),
    ]
