# Generated by Django 4.0.10 on 2024-07-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmanager',
            name='phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
