# Generated by Django 4.0 on 2022-01-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webank', '0002_alter_accountmanager_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmanager',
            name='marital_status',
        ),
        migrations.AlterField(
            model_name='accountmanager',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Binary', 'Binary')], default=0, max_length=50),
        ),
    ]
