# Generated by Django 4.0 on 2022-01-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webank', '0003_remove_accountmanager_marital_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmanager',
            name='account_type',
            field=models.CharField(choices=[('Savings account', 'Savings account'), ('Current Account', 'Current Account'), ('Fixed Account', 'Fixed Account')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='accountmanager',
            name='address',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accountmanager',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Binary', 'Binary')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accountmanager',
            name='occupation',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
