# Generated by Django 4.0 on 2022-01-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webank', '0004_alter_accountmanager_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmanager',
            name='fullname',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
