# Generated by Django 4.0 on 2022-01-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webank', '0006_alter_accountmanager_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmanager',
            name='account_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
