# Generated by Django 4.0 on 2022-01-06 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webank', '0008_alter_accountmanager_phone_number_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='customer_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webank.accountmanager'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webank.user'),
        ),
    ]
